package org.nsu.fit.tests.api;

import org.nsu.fit.services.rest.RestClient;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.util.List;

public class CreateCustomerTest {
    private AccountTokenPojo adminToken;
    private RestClient client;

    @BeforeClass
    public void before() {
        client = new RestClient();
        adminToken = new RestClient().authenticate("admin", "setup");
    }

    @Test
    public void createCustomerTest() {
        CustomerPojo customerPojo = client.createAutoGeneratedCustomer(adminToken);
        List<CustomerPojo> customers = client.getCustomerByLogin(customerPojo.login, null);
        Assert.assertTrue(customers.contains(customerPojo));
    }

    @Test
    public void createCustomerWithErrorTest() {
        CustomerPojo customerPojo = client.createCustomerWithEasyPassword(adminToken);
        // todo check
        List<CustomerPojo> customers = client.getCustomerByLogin(customerPojo.login, null);
        Assert.assertTrue(customers.contains(customerPojo));
    }
}
